[0m14:18:12.116367 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10744e120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111c03ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111c03d90>]}


============================== 14:18:12.118884 | 0abc8111-78e2-496e-9890-7f7889e4f73f ==============================
[0m14:18:12.118884 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:18:12.119191 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/justin.david/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init ae-bootcamp', 'send_anonymous_usage_stats': 'True'}
[0m14:18:50.338217 [debug] [MainThread]: Starter project path: /Users/justin.david/analytics-engineer-bootcamp/dbt-env/lib/python3.13/site-packages/dbt/include/starter_project
[0m14:18:50.349669 [info ] [MainThread]: 
Your new dbt project "ae_bootcamp" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:18:50.350209 [info ] [MainThread]: Setting up your profile.
[0m14:20:47.551628 [info ] [MainThread]: Profile ae_bootcamp written to /Users/justin.david/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:20:47.650993 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 155.5672, "process_user_time": 0.922207, "process_kernel_time": 0.289982, "process_mem_max_rss": "180174848", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:20:47.652776 [debug] [MainThread]: Command `dbt init` succeeded at 14:20:47.652095 after 155.57 seconds
[0m14:20:47.656537 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x122850770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111abc290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x122c26f10>]}
[0m14:20:47.658339 [debug] [MainThread]: Flushing usage events
[0m14:21:07.273894 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10444e120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f03ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f03d90>]}


============================== 14:21:07.276839 | 80592750-e1ba-436c-ac1c-753bf036fb21 ==============================
[0m14:21:07.276839 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:21:07.277156 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/justin.david/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:21:07.288774 [info ] [MainThread]: dbt version: 1.8.7
[0m14:21:07.289003 [info ] [MainThread]: python version: 3.13.0
[0m14:21:07.289135 [info ] [MainThread]: python path: /Users/justin.david/analytics-engineer-bootcamp/dbt-env/bin/python3.13
[0m14:21:07.289250 [info ] [MainThread]: os info: macOS-14.0-arm64-arm-64bit-Mach-O
[0m14:21:08.005851 [info ] [MainThread]: Using profiles dir at /Users/justin.david/.dbt
[0m14:21:08.006118 [info ] [MainThread]: Using profiles.yml file at /Users/justin.david/.dbt/profiles.yml
[0m14:21:08.006258 [info ] [MainThread]: Using dbt_project.yml file at /Users/justin.david/analytics-engineer-bootcamp/dbt_project.yml
[0m14:21:08.006406 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:21:08.008246 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.7910207, "process_user_time": 0.984856, "process_kernel_time": 0.251645, "process_mem_max_rss": "194347008", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:21:08.008508 [debug] [MainThread]: Command `dbt debug` failed at 14:21:08.008456 after 0.79 seconds
[0m14:21:08.008672 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x116d4ac40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1163c15b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x116dd8050>]}
[0m14:21:08.008841 [debug] [MainThread]: Flushing usage events
[0m14:25:38.880283 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102572120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103ed7ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103ed7d90>]}


============================== 14:25:38.883718 | 593439e8-9dc2-45e6-bfae-399150f03dd3 ==============================
[0m14:25:38.883718 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:25:38.884107 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/justin.david/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:25:38.895987 [info ] [MainThread]: dbt version: 1.8.7
[0m14:25:38.896215 [info ] [MainThread]: python version: 3.13.0
[0m14:25:38.896354 [info ] [MainThread]: python path: /Users/justin.david/analytics-engineer-bootcamp/dbt-env/bin/python3.13
[0m14:25:38.896477 [info ] [MainThread]: os info: macOS-14.0-arm64-arm-64bit-Mach-O
[0m14:25:39.620238 [info ] [MainThread]: Using profiles dir at /Users/justin.david/.dbt
[0m14:25:39.620488 [info ] [MainThread]: Using profiles.yml file at /Users/justin.david/.dbt/profiles.yml
[0m14:25:39.620631 [info ] [MainThread]: Using dbt_project.yml file at /Users/justin.david/analytics-engineer-bootcamp/dbt_project.yml
[0m14:25:39.620782 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:25:39.622649 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.8223829, "process_user_time": 0.934769, "process_kernel_time": 0.23876, "process_mem_max_rss": "192184320", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:25:39.622917 [debug] [MainThread]: Command `dbt debug` failed at 14:25:39.622865 after 0.82 seconds
[0m14:25:39.623088 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a17ac40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109af15b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a208050>]}
[0m14:25:39.623261 [debug] [MainThread]: Flushing usage events
[0m14:26:46.786235 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e5e120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087c3ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087c3d90>]}


============================== 14:26:46.789566 | 825f5ac5-a2d5-406c-938d-3fe6842bb45f ==============================
[0m14:26:46.789566 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:26:46.789948 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/justin.david/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run --profile ae_bootcamp', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:26:46.790275 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/justin.david/analytics-engineer-bootcamp/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:26:46.791825 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.07681904, "process_user_time": 0.589381, "process_kernel_time": 0.123438, "process_mem_max_rss": "96944128", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:26:46.792187 [debug] [MainThread]: Command `dbt run` failed at 14:26:46.792125 after 0.08 seconds
[0m14:26:46.792391 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087fd220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108541eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1084b3ac0>]}
[0m14:26:46.792569 [debug] [MainThread]: Flushing usage events
[0m14:27:21.945244 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10524e120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107303ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107303d90>]}


============================== 14:27:21.948062 | 03911dd7-30fd-4785-b26b-3b16c0171b8b ==============================
[0m14:27:21.948062 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:27:21.948377 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/justin.david/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:27:21.958750 [info ] [MainThread]: dbt version: 1.8.7
[0m14:27:21.958943 [info ] [MainThread]: python version: 3.13.0
[0m14:27:21.959072 [info ] [MainThread]: python path: /Users/justin.david/analytics-engineer-bootcamp/dbt-env/bin/python3.13
[0m14:27:21.959184 [info ] [MainThread]: os info: macOS-14.0-arm64-arm-64bit-Mach-O
[0m14:27:22.659751 [info ] [MainThread]: Using profiles dir at /Users/justin.david/.dbt
[0m14:27:22.660007 [info ] [MainThread]: Using profiles.yml file at /Users/justin.david/.dbt/profiles.yml
[0m14:27:22.660145 [info ] [MainThread]: Using dbt_project.yml file at /Users/justin.david/analytics-engineer-bootcamp/dbt_project.yml
[0m14:27:22.660291 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:27:22.662061 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.7534064, "process_user_time": 0.925764, "process_kernel_time": 0.230601, "process_mem_max_rss": "191496192", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:27:22.662294 [debug] [MainThread]: Command `dbt debug` failed at 14:27:22.662247 after 0.75 seconds
[0m14:27:22.662456 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11664ac40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x115cc15b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1166d8050>]}
[0m14:27:22.662622 [debug] [MainThread]: Flushing usage events
[0m14:28:58.963342 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10520a120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106b6fed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106b6fd90>]}


============================== 14:28:58.966204 | 63b28b3c-0bf8-4818-b783-8468d92d7fb4 ==============================
[0m14:28:58.966204 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:28:58.966512 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/justin.david/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m14:28:58.977013 [info ] [MainThread]: dbt version: 1.8.7
[0m14:28:58.977215 [info ] [MainThread]: python version: 3.13.0
[0m14:28:58.977343 [info ] [MainThread]: python path: /Users/justin.david/analytics-engineer-bootcamp/dbt-env/bin/python3.13
[0m14:28:58.977459 [info ] [MainThread]: os info: macOS-14.0-arm64-arm-64bit-Mach-O
[0m14:28:59.671012 [info ] [MainThread]: Using profiles dir at /Users/justin.david/.dbt
[0m14:28:59.671269 [info ] [MainThread]: Using profiles.yml file at /Users/justin.david/.dbt/profiles.yml
[0m14:28:59.671403 [info ] [MainThread]: Using dbt_project.yml file at /Users/justin.david/analytics-engineer-bootcamp/dbt_project.yml
[0m14:28:59.671557 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:28:59.673349 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.74735826, "process_user_time": 0.925777, "process_kernel_time": 0.216953, "process_mem_max_rss": "192708608", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:28:59.673595 [debug] [MainThread]: Command `dbt debug` failed at 14:28:59.673544 after 0.75 seconds
[0m14:28:59.673756 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ce12c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c7895b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ceb0050>]}
[0m14:28:59.673920 [debug] [MainThread]: Flushing usage events
